//
// Created by huli on 2020/11/12.
//

#ifndef DISKSPEEDTEST_SEQUENCE_WRITE_FIX_SET_FIX_WRITE_H
#define DISKSPEEDTEST_SEQUENCE_WRITE_FIX_SET_FIX_WRITE_H

#endif //DISKSPEEDTEST_SEQUENCE_WRITE_FIX_SET_FIX_WRITE_H
